services:
  tests:
    build: .
    image: my-tests:latest

  smoke-tests:
    image: my-tests:latest
    command: pytest -n 4 -m smoke
  regression-tests:
    image: my-tests:latest
    command: pytest -n 4 -m regression