[pytest]

markers =
    smoke: основная функциональность сервиса
    regression: все тесты для полной проверки функциональности

addopts =
    --alluredir=allure-results
    --reruns=2
    --reruns-delay=1
    -n 4