name: Github CI with Local Runner

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run_tests:
    runs-on: self-hosted
    steps:
      - name: 📥 Чекаут кода
        uses: actions/checkout@v4

      - name: 🔧 Подготовка окружения
        run: |
          python -m venv venv
          .\venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🧪 Запуск тестов
        run: |
          .\venv\Scripts\Activate.ps1
          pytest tests/ --alluredir=./allure-results --clean-alluredir -v
        continue-on-error: true
        env:
          TOKEN: ${{ secrets.TOKEN }}


      - name: 📊 Генерация Allure HTML
        if: always()
        run: allure generate ./allure-results -o ./allure-report --clean

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.SECRET_NEW }}
          publish_dir: ./allure-report

      - name: 🔗 Ссылка на Allure Отчет
        run: |
          $REPORT_URL = "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
          Write-Output "Отчет успешно опубликован!"
          Write-Output "Открыть Allure: $REPORT_URL"