name: GitVerse CI with Local Runner

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run_tests:
#    tags:
#      img-ubuntu-20.04 # Здесь мы указываем label твоего поднятого раннера
    runs-on: self-hosted
    steps:
      - name: 📥 Чекаут кода
        uses: actions/checkout@v4

      - name: 🔧 Подготовка окружения
        run: |
          python -m venv venv
          .\venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🧪 Запуск тестов
        run: |
          .\venv\Scripts\Activate.ps1
          pytest tests/ --alluredir=./allure-results --clean-alluredir -v
        continue-on-error: true
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: 📊 Генерация Allure HTML
        if: always()
        run: allure generate ./allure-results -o ./allure-report --clean

      - name: 📤 Загрузка отчета в артефакты
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      # 2. Новый шаг: скачиваем артефакт для публикации
      - name: 📥 Скачивание артефакта для Pages
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: ./pages-artifact

      # 3. Загружаем артефакт в Pages
      - name: 📤 Загрузка в GitVerse Pages
        if: always()
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./pages-artifact


      - name: 🚀 Публикация в GitVerse Pages (ветка gh-pages )
        if: always()
        env:
          TOKEN: ${{ secrets.SECRET_TOKEN }}
        with:
          TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: |
          Remove-Item -Recurse -Force /tmp/allure-report
          Copy-Item -Recurse ./allure-report /tmp/allure-report
          git config --global user.name "GitVerse CI"
          git config --global user.email "ci@gitverse.ru"
          git checkout -B gh-pages
          Get-ChildItem -Exclude .git | Remove-Item -Recurse -Force
          Copy-Item -Recurse /tmp/allure-report/* ./
          git add .
          git commit -m "Deploy Allure Report to Pages"
          git push https://$env:TOKEN@gitverse.ru/Kirill-Kamyshanov/memes gh-pages --force


      - name: 🔗 Ссылка на Allure Отчет
        if: success()
        run: |
          REPORT_URL="https://${{ github.repository_owner }}.gitverse.site/${{ github.event.repository.name }}/"
          echo "Отчет успешно опубликован!"
          echo "Открыть Allure: $REPORT_URL"
          echo "Ссылка на отчет: $REPORT_URL"